# Generated by Django 2.2.7 on 2020-04-08 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PicTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_pic', models.ImageField(upload_to='booktest')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_imag', models.ImageField(blank=True, null=True, upload_to='user_img/', verbose_name='用户头像')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('que_text', models.CharField(max_length=1000)),
                ('que_title', models.CharField(max_length=50)),
                ('que_like', models.IntegerField(default=0)),
                ('que_time', models.DateTimeField(blank=True, null=True)),
                ('que_imag', models.ImageField(blank=True, null=True, upload_to='question_img/', verbose_name='问题图片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=30)),
                ('pet_age', models.IntegerField(default=0)),
                ('pet_sex', models.CharField(choices=[('male', '公'), ('female', '母')], default='公', max_length=32)),
                ('pet_imag', models.ImageField(blank=True, null=True, upload_to='pet_img/', verbose_name='宠物图片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('dynamic_id', models.AutoField(primary_key=True, serialize=False)),
                ('dyn_text', models.CharField(max_length=1000)),
                ('dyn_title', models.CharField(max_length=50)),
                ('dyn_like', models.IntegerField(default=0)),
                ('dyn_time', models.DateTimeField(blank=True, null=True)),
                ('dyn_imag', models.ImageField(blank=True, null=True, upload_to='dynamic_img/', verbose_name='动态图片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('discuss_id', models.AutoField(primary_key=True, serialize=False)),
                ('dis_text', models.CharField(default=' ', max_length=1000)),
                ('dis_like', models.IntegerField(default=0)),
                ('dis_time', models.DateTimeField(blank=True, null=True)),
                ('dynamic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Dynamic')),
            ],
        ),
    ]
