# Generated by Django 2.2.7 on 2020-04-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamic',
            name='dyn_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
