# Generated by Django 2.2.7 on 2020-04-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200408_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_sex',
            field=models.CharField(choices=[('male', '男孩'), ('female', '女孩')], default='男孩', max_length=32),
        ),
    ]
