# Generated by Django 2.2.7 on 2020-04-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200408_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_sex',
            field=models.CharField(choices=[('男孩', '男孩'), ('女孩', '女孩')], default='男孩', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=32),
        ),
    ]
