# Generated by Django 2.2.7 on 2020-05-05 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0011_auto_20200505_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_text', models.TextField()),
                ('com_time', models.DateTimeField(auto_now_add=True)),
                ('dynamic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='login.Dynamic')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='login.User')),
            ],
            options={
                'ordering': ('com_time',),
            },
        ),
    ]
